### ISSUE TITLE
Bundle exec devpack install gives `No gems to install.`

### ISSUE THREAD

**Issue by brkn** [bobf/devpack#4]
### Problem

To avoid running commands from different version of installed gems, it's suggested to run `bundle exec gem`. Devpack doesn't handle this.

Installed version:
`gem 'devpack', '~> 0.4.0'`
`Bundler version 2.3.11`
`ruby 2.6.9p207 (2021-11-24 revision 67954) [arm64-darwin20]`

#### Steps to reproduce

1. Create a devpack file `echo pry >> .devpack`
2. Run `bundle exec devpack install`
3. Prints `[devpack] No gems to install.`

#### Expected behaviour

Install devpack dependencies inside the current directory.

**Comment by bobf** [comment]
I tried to recreate this but was unsuccessful. Could you provide more context ? Can you confirm that `pry` is definitely not installed and available ?

```
$ echo pry >> .devpack
```

```
$ bundle exec devpack install
[devpack] [exec] bundle exec gem install -V pry
invalid options: -SNw2
(invalid options are ignored)
Parsing sources...

# [snip]

pid 2772941 exit 0
[devpack] Installation complete.
```

```
$ bundle exec irb
irb(main):001:0> require 'devpack'
[devpack] ✓ Loaded 1 development gem(s) from /tmp/devpacktest/.devpack in 0.11 seconds.                                                     
=> true                                                               
irb(main):002:0> binding.pry
[1] pry(main)> 
```

**Comment by brkn** [comment]
Can't recreate consistently either now, I'm going to recreate this issue when I recounter this.
